### ISSUE TITLE
Create scripts using the new Python API

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/SimVascular#678]
We would like to create scripts using the new Python API. 

The new scripts will come from 

1) rewriting scripts using the previous Python API

2) Rewriting scripts using the previous Tcl API

3) New examples

**Comment by neilbalch** [comment]
I've been working on converting my scripts and beginning to learn how the new API works. However, I'm a bit stuck. Consider the following lines:

```python
contour_group_name = 'test-seg'
contour_ids = range(0, 1)

path_name = "test-path"
path = sv.pathplanning.Path()
path.add_control_point([0.0, 0.0, 0.0])
path.add_control_point([0.0, 0.0, 5.0])

curve_frame = path.get_curve_frame(0)

segmentations = [sv.segmentation.Circle(radius = 5.0, frame=curve_frame)]

center = segmentations[0].get_center()
print("  Center: {0:g} {1:g} {2:g}".format(center[0], center[1], center[2]))

sv.dmg.add_path(name=path_name, path=path)
sv.dmg.add_segmentation(name=contour_group_name, path=path_name, segmentations=segmentations)
```

I would expect this script to create a path with two points, one at (0,0,0) and one at (0,0,5) and then create a circular segmentation on the first point with a radius of 5. However, when I look at the resulting path and segmentation in the data manager, only the path is rendered. The circle contour point 0 is recognized, but not drawn in the display.

![image](https://user-images.githubusercontent.com/3847882/85328184-243f4e00-b485-11ea-8e1d-b5c1df95c932.png)

This confuses me because I believe I've lifted all of the commands I used to generate the path and segmentation and then send them to the data manager from two of your example scripts. (sources for commands to [upload segmentations to DMG](https://github.com/ktbolt/sv-python-api/blob/master/tests/dmg/add-segmentation.py) and [create circular contours](https://github.com/ktbolt/sv-python-api/blob/cb085e11c46311ecc2a30cf79bb9e899c3d1db00/tests/segmentation/circle-path.py)) Any ideas as to what could be causing this?

### EDIT:

I've been able to locate the Python class definitions for the `sv.dmg.add_segmentation(name=contour_group_name, path=path_name, segmentations=segmentations)` method call in light of Dave's mention that the resulting `.ctg` for the contour group looks like this:

```xml
        davep> cat Segmentations/test-seg.ctgr 
        <?xml version="1.0" encoding="UTF-8" ?>
        <format version="1.0" />
        <contourgroup path_name="test-path" path_id="6" reslice_size="5" point_2D_display_size="" point_size="">
            <timestep id="0">
                <lofting_parameters method="nurbs" sampling="60" sample_per_seg="12" use_linear_sample="1" linear_multiplier="10" use_fft="0" num_modes="20" u_degree="2" v_degree="2" u_knot_type="derivative" v_knot_type="average" u_parametric_type="centripetal" v_parametric_type="chord" />
                <contour id="0" type="Contour" method="Manual" closed="true" min_control_number="2" max_control_number="2" subdivision_type="0" subdivision_number="0" subdivision_spacing="0">
                    <path_point id="0">
                        <pos x="0.271689448304079" y="0" z="0" />
                        <tangent x="1" y="0" z="1" />
                        <rotation x="-0" y="7.4109846876187e-323" z="0" />
                    </path_point>
                    <control_points>
                        <point id="0" x="nan" y="nan" z="nan" />
                        <point id="1" x="nan" y="nan" z="nan" />
                    </control_points>
                    <contour_points />
                </contour>
            </timestep>
        </contourgroup>
```

However, I haven't been able to locate the offending code segments responsible for this specific issue. I unfortunately haven't been able to make sense of the API code yet.

**Comment by ktbolt** [comment]
@neilbalch I went over to https://github.com/SimVascular/SimVascular/issues/595 and searched for **circle** and found a comment I made on May 14
```
Several implementation issues in SV is making the segmentation module difficult to implement.
.
.
.
I'm not sure what to do here, have to give it a think.
```
So it seems that the **segmentation** module may be half baked. 

The circle segmentation API code is in **SegmentationCircle_PyClass.cxx**. If you look in **PyCircleSegmentationInit** you will see that the code to set circle data is commented out
```
/*
  auto circleContour = (sv3::circleContour*)(self->super.contour);

  // Set circle data if it has been given.
  //
  if (kwargs != nullptr) {

      // Set the circle path point if it is given, else set its plane geometry.
      //
      if (frameArg != nullptr) {
          circleContour->SetPathPoint(pathPoint);
      } else { 
          auto plane = vtkSmartPointer<vtkPlane>::New();
          plane->SetOrigin(center.data());
          plane->SetNormal(normal.data());
          circleContour->SetPlaneGeometry(plane);
      }

      // Set the circle point and radius.
      //
      // The circle center is set to the projection of the 'point' 
      // onto the given plane or frame.
      //
      circleContour->SetControlPointByRadius(radius, center.data());
  }
*/
```
because it was crashing when reading in a .ctgr file.

When writing or converting Python scripts first look at the code that implements the classes you will use to see if there is anything screwy going on; I'll sometimes add a **TODO** comment or **Note** comment. You should also be testing the docstrings for the class to see if they make sense.

Look at the code in **SegmentationCircle_PyClass.cxx** and see how it works and try to create circle segmentations using Circle class methods.

**Comment by neilbalch** [comment]
Hrm, I see. I'm not sure how to continue on with converting most of my scripts, as they tend to lean on the segmentation module's functionality quite heavily.

On a different note, I found a bug with the python interpreter window in SV when the desktop environment is set to use a dark theme that causes the text to blend in with the black background.  I'd love to try and track this down and submit a patch that changes the text color in the python interpreter window when the desktop theme is changed to dark, but I can't seem to find the source code for the appearance of the "Python console" window anywhere is the codebase. @ktbolt, do you happen to know by chance? I've tried `git grep "Python Console"`, the name of the window in the SV GUI, and others but no search results come up.

**Comment by ktbolt** [comment]
@neilbalch You should still be able to create segmentations, just need to set the data that the segmentation type needs. You can also read in a **.ctgr** file that doesn't have circle contours I think.

I have tried to simplify the API and hide SV implementation details, like a circle is defined by controls points rather than a center and a radius. The methods used in your scripts may no longer exist or have been renamed. You will need to figure out how to create the same segmentations using the new API.

Open an Issue for the Python interpreter window problem. The Python console is probably implemented within MITK. @fkong7 Do you know anything about this?

**Comment by neilbalch** [comment]
I respect your decision, @ktbolt, but as an end-user, I would think that the opposite is true and that defining a circle by a center and radius is more intuitive and hides more SV implementation details than defining it manually using control points.

Also, isn't the center and radius paradigm how circle segmentations are defined by the user in the SV GUI or am I forgetting something?

**Comment by neilbalch** [comment]
Hrm. Something else interesting seems to have occurred during a system update (`sudo apt update && sudo apt full-upgrade -y`). I can no longer build the project:

```bash
neil@neil-VirtualBox:~/SimVascular/build$ make -j 8
[ 50%] Built target Externals
[ 56%] Performing configure step for 'SimVascular'
loading initial cache file /home/neil/SimVascular/build/SimVascular-prefix/tmp/SimVascular-cache-Release.cmake
CMake Deprecation Warning at CMakeLists.txt:56 (cmake_policy):
  The OLD behavior for policy CMP0025 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- SimVascular Version: simvascular 2020-07-03
SV_BUILD_TYPE_DIR: release
-- Performing Test HAS_FLAG_-std=c11
-- Performing Test HAS_FLAG_-std=c11 - Success
Externals/Qt5.cmake Qt5_DIR initial value: /opt/Qt5.11.3/5.11.3/gcc_64/lib/cmake/Qt5
Externals/Qt5.cmake Qt5_DIR final value: /home/neil/SimVascular/build/Externals-build/svExternals/bin/qt-5.11.3/5.11.3/gcc_64/lib/cmake/Qt5
CMake Error at CMake/SimVascularMacros.cmake:142 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.11.3) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMake/Externals/Qt5.cmake:133 (simvascular_external)
  CMake/SimVascularExternals.cmake:37 (include)
  CMakeLists.txt:122 (include)


-- Configuring incomplete, errors occurred!
See also "/home/neil/SimVascular/build/SimVascular-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/SimVascular.dir/build.make:106: recipe for target 'SimVascular-prefix/src/SimVascular-stamp/SimVascular-configure' failed
make[2]: *** [SimVascular-prefix/src/SimVascular-stamp/SimVascular-configure] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/SimVascular.dir/all' failed
make[1]: *** [CMakeFiles/SimVascular.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
neil@neil-VirtualBox:~/SimVascular/build$ 
```

I don't remember doing anything with the Cmake config files for Qt. 😕

**Comment by neilbalch** [comment]
@ktbolt I seem to have forgotten since last summer, how do I use `make` to rebuild only the changed source files instead of forcing it to rebuild _everything_?

I pulled your latest changes to the python API, and when I ran `make -j 8` as usual, it reported that there was nothing new to build. I had to force a rebuild using the `-B` flag.

Is the python API source code structured in such a manner that rebuilds are unnecessary for implementing interface changes?

**Comment by ktbolt** [comment]
@neilbalch In the build directory you need to 
```
cd SimVascular-build
make
```

**Comment by neilbalch** [comment]
@ktbolt Huh, that's interesting. Do you know why?

**Comment by ktbolt** [comment]
@neilbalch To debug things like this you should start from the source, which in this case is the CircleSegmentation code, and see what it is doing, put in some print statements.

**Comment by neilbalch** [comment]
@ktbolt I'm really having a hard time tracking down the issue here with my limited knowledge of how the new API is structured and relying on probing with print statements. I've confirmed a couple of suspicions about the `sv.segmentation.Circle()` constructor (_aka. `PyCircleSegmentationInit()`_) function which appears to be tripping up:

- All three of the `radius`, `center`, and `normal` arguments are being received and processed, but the `center` argument is read as `[0, 0, 1]` instead of what it was passed as `[0, 0, 0]`
    - I don't know how important this is to the process of finding the solution
- Once I pulled the latest changes from the `ktbolt:improve-python-api_552` branch, _(as of this morning)_ SimVascular is no longer able to save the demo project after the Python script is run; it hangs at 50% save completion

**Comment by ktbolt** [comment]
@neilbalch When you pull down a new branch it is a good idea to remove the build directory and build from scratch. You should also remove the contents of $HOME/.local/share/SimVascular. This is were the MITK database is stored for SV, sometimes causes problems if multiple SV versions have been run.

I've added a new branch named **Create-object-based-interface-python-api_595**, it is the one I'm merging into master so use this guy.

The new API structure is pretty simple: modules and classes. Have a look at the readme.md here https://github.com/ktbolt/SimVascular/tree/Create-object-based-interface-python-api_595/Code/Source/PythonAPI for an overview.

It is easier to test the API from the command line I think, I never use the console unless I am testing the **dmg** module.

**Comment by neilbalch** [comment]
So `Create-object-based-interface-python-api_595` is the one to use?

> It is easier to test the API from the command line I think, I never use the console unless I am testing the dmg module.

How does that work?

**Comment by ktbolt** [comment]
@neilbalch What, you've never run scripts from the command line?! You've been missing all the fun!

This is how the fun begins 
```
sv --python -- script.py
```
Where **sv** is something like
```
alias sv='$HOME/SimVascular/build/SimVascular-build/sv'
```

**Comment by neilbalch** [comment]
> You should also remove the contents of $HOME/.local/share/SimVascular. This is were the MITK database is stored for SV, sometimes causes problems if multiple SV versions have been run.

Unfortunately, that doesn't solve the save crashing at 50% issue. ☹️

**Comment by ktbolt** [comment]
@neilbalch Post the script you are using to create the circle segmentation.

**Comment by neilbalch** [comment]
Nevermind, sorry for bothering you! Removing `$HOME/.local/share/SimVascular` _AND_ rebuilding solved the issue. 🤦

**Comment by neilbalch** [comment]
For the record, I was working with this: https://github.com/neilbalch/SimVascular-pythondemos/blob/master/contour_radii.py

**Comment by neilbalch** [comment]
@ktbolt I'm working through one of my lofting/solid modeling scripts, and I can't figure out how to translate the old API commands into new ones; I don't see the same behaviors implemented. I see [this example script of yours](https://github.com/ktbolt/sv-python-api/blob/master/tests/geometry/loft.py), but it only helps with the first part of the process.

This is the script I'm working to ocnvert: https://github.com/neilbalch/SimVascular-pythondemos/blob/master/contour_to_lofted_model.py

**Comment by ktbolt** [comment]
@neilbalch What is the first part of the process?

The new API seems to have all of the things you need

```
Geom.LoftSolid()  ---->    sv.geometry.loft()

VMTKUtils.Cap_with_ids() ---->  sv.vmtk.cap_with_ids()

Geom.Union() ----> modeler.union()
```

The lofting process is
1. Create segmentation contours
2. Align the contours so they have the same start position looking down their axes
3. Create a lofter surface from the aligned contours
4. Add caps to the lofted surface to create a solid model

Once you have the solid model you can union it with other models.

**Comment by neilbalch** [comment]
Well, you example script for lofting has a few other intermediary steps: https://github.com/ktbolt/sv-python-api/blob/master/tests/geometry/loft.py like this:

```python
for cid in range(start_cid,end_cid):
    cont_ipd = sv_contour.get_profile_contour(gr, renderer, contours, cid, num_profile_points)
    if cid == start_cid:
        cont_align = cont_ipd 
    else:
        cont_align = sv.geometry.align_profile(last_cont_align, cont_ipd, use_distance)
    contour_list.append(cont_align) 
    sv_contour.add_sphere(gr, renderer, cont_align, radius)
    last_cont_align = cont_align
```

and I don't see any examples for how to use the `modeler.union()` method. Many of [your tests are sparsely commented](https://github.com/ktbolt/sv-python-api/tree/master/tests).

**Comment by neilbalch** [comment]
Hey @ktbolt do you think you'll have any time soon to help me iron out the complete workflow for this process? I still don't think I really have a complete enough understanding about the exact required I/O and types to the methods you described in your previous post. Thanks!

**Comment by ktbolt** [comment]
@neilbalch There is a **union** example in https://github.com/ktbolt/sv-python-api/blob/master/tests/modeling/boolean-union.py

But this is not working, something going on with kernel IDs, I will fix.

Let's meet on Zoom Tuesday at 2pm if you can.

**Comment by neilbalch** [comment]
> Let's meet on Zoom Tuesday at 2pm if you can.

Okay, @ktbolt! You mean tomorrow, right? That works for me, just please send the zoom meeting link or calendar invite to neilbalch@gmail.com.

**Comment by ktbolt** [comment]
The **Modeler** **union** method is working again, was passing in the wrong type **PyModelingModel** instead of **PyModelingModeler**
```
ModelingModeler_union(PyModelingModel* self, PyObject* args, PyObject* kwargs)
```
Note that **self**'s type can be defined using **ANY** type derived from PyObject.

**Comment by neilbalch** [comment]
Hey @ktbolt I've run into an issue while trying to make use of methods that require:

```python
import graphics as graph
```

where my local Python interpreter in SimVascular doesn't know what the `graphics` package is or where to get it. AFAIK, `graphics` isn't a pagkage I can simply acquire from `pip3`... do you know where to get/find it?

**Comment by neilbalch** [comment]
Also, @ktbolt, I'm having a hard time figuring out why the `sv.vmtk.cap_with_ids` method call is crashing in [this WIP script conversion](https://github.com/neilbalch/SimVascular-pythondemos/blob/master/contour_to_lofted_model.py).

AFAIK I've been following the process of the example scripts you showed me in our Zoome meeting last week to the letter, but evidently I'm not understanding this properly. To finish the process of lofting the surface and creating a solid model/mesh _(I'm still not sure what the end result is and what category it would fall under in the SV DMG... please help!)_, I need to cap the surface so it forms an enclosed volume:

```python
    # Cap the lofted volume.
    sv.vmtk.cap_with_ids(surface=lofted_surface, fill_id=1, increment_id=True)
```

I've verified that the `lofted_surface` object is a `vtkPolyData` object and has a sane amount of polygons in it:

```python
>>> print(lofted_surface)
vtkPolyData (0x559df3118af0)
  Debug: Off
  Modified Time: 9967537
  Reference Count: 2
  Registered Events: (none)
  Information: 0x559df30f4960
  Data Released: False
  Global Release Data: Off
  UpdateTime: 0
  Field Data:
    Debug: Off
    Modified Time: 9967529
    Reference Count: 1
    Registered Events: (none)
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
  Number Of Points: 1250
  Number Of Cells: 2450
  Cell Data:
    Debug: Off
    Modified Time: 9967532
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x559df30f3030)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x559df30f4520
          Priority: 0
          Tag: 1
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )
    Interpolate Flags: ( 1 1 1 1 1 0 0 1 )
    Pass Through Flags: ( 1 1 1 1 1 1 1 1 )
    Scalars: (none)
    Vectors: (none)
    Normals: (none)
    TCoords: (none)
    Tensors: (none)
    GlobalIds: (none)
    PedigreeIds: (none)
    EdgeFlag: (none)
  Point Data:
    Debug: Off
    Modified Time: 9967531
    Reference Count: 1
    Registered Events: 
      Registered Observers:
        vtkObserver (0x559df30f38b0)
          Event: 33
          EventName: ModifiedEvent
          Command: 0x559df30f4520
          Priority: 0
          Tag: 1
    Number Of Arrays: 0
    Number Of Components: 0
    Number Of Tuples: 0
    Copy Tuple Flags: ( 1 1 1 1 1 0 1 1 )
    Interpolate Flags: ( 1 1 1 1 1 0 0 1 )
    Pass Through Flags: ( 1 1 1 1 1 1 1 1 )
    Scalars: (none)
    Vectors: (none)
    Normals: (none)
    TCoords: (none)
    Tensors: (none)
    GlobalIds: (none)
    PedigreeIds: (none)
    EdgeFlag: (none)
  Bounds: 
    Xmin,Xmax: (-4.92063, 5.21991)
    Ymin,Ymax: (-5.06727, 5.07343)
    Zmin,Zmax: (53.9176, 53.9751)
  Compute Time: 9967559
  Number Of Points: 1250
  Point Coordinates: 0x559df30ce3b0
  Locator: 0
  Number Of Vertices: 0
  Number Of Lines: 0
  Number Of Polygons: 2450
  Number Of Triangle Strips: 0
  Number Of Pieces: 1
  Piece: -1
  Ghost Level: 0
>>> print(type(lofted_surface))
<class 'vtkCommonDataModelPython.vtkPolyData'>
```

I'm not sure how to debug what's going wrong... I'm working through reading the C++ source, but as we've discussed, it's quite dense and confusing for me. Could you please help me with this?

**Comment by neilbalch** [comment]
@ktbolt **_UPDATE:_** After pulling the latest changes from `ktbolt:Create-object-based-interface-python-api_595`, the issue appears to have moved up the chain to when the contour PolyData is being extracted using the `segmentation.Circle.get_polydata()` method. This method call returns `None`, even though the`segmentation.Circle` object was constructed properly.

[The script](https://github.com/neilbalch/SimVascular-pythondemos/blob/master/contour_to_lofted_model.py )now prints the following when executed:

```python
path_point_id: 0
<segmentation.Circle object at 0x7f2ff13686c0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 10
<segmentation.Circle object at 0x7f2f8c1419f0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 20
<segmentation.Circle object at 0x7f2ff13686c0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 30
<segmentation.Circle object at 0x7f2f8c1419f0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 40
<segmentation.Circle object at 0x7f2ff13686c0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 50
<segmentation.Circle object at 0x7f2f8c1419f0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 60
<segmentation.Circle object at 0x7f2ff13686c0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 70
<segmentation.Circle object at 0x7f2f8c1419f0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 80
<segmentation.Circle object at 0x7f2ff13686c0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

path_point_id: 90
<segmentation.Circle object at 0x7f2f8c1419f0>
<class 'segmentation.Circle'>
None
<class 'NoneType'>

index: 0
<class 'NoneType'>
Traceback (most recent call last):
  File "<string>", line 147, in <module>
  File "<string>", line 65, in create_solid_from_path
geometry.Error: Geom.interpolate_closed_curve() The polydata argument is not a vtkPolyData object.
```

**Comment by ktbolt** [comment]
@neilbalch 

**graphics** is a module I wrote for my testing scripts, see https://github.com/ktbolt/sv-python-api/tree/master/tests/graphics. 

The scripts should all include this module using
```
    sys.path.insert(1, '../graphics/')
    import graphics as gr
```


I'm not sure why **sv.vmtk.cap_with_ids** crashes. The SV code sometimes prints messages to stderr. Do you see any other messages? I typically try to catch argument problems in the API before I send them to the SV functions. Go ahead and add some error checking to the input vtkPolyData to **sv.vmtk.cap_with_ids** , maybe the input data is bad.

**segmentation.Circle.get_polydata()** returns None seems to be a vtk problem. Are you importing vtk?

**Comment by ktbolt** [comment]
I had planned on adding the **graphics** module to **sv**, wanted to give it a bit more thought before I did that though.

**Comment by neilbalch** [comment]
@ktbolt 

> The SV code sometimes prints messages to stderr. Do you see any other messages?

No, I haven't seen any other error messages logged.

> Go ahead and add some error checking to the input vtkPolyData to sv.vmtk.cap_with_ids

I've thought about doing that, but I don't know where to start or how to instrument like that in vtk objects.

> Are you importing vtk?

Yes, I am. [This is the script](https://github.com/neilbalch/SimVascular-pythondemos/blob/master/contour_to_lofted_model.py) I've been working on.

**Comment by ktbolt** [comment]
I'm not sure what **how to instrument like that in vtk objects** means but you just need to check that the **PolyData** has points and cells, write out a pleasing error message if it doesn't.

I don't see an **import vtk** statement in the https://github.com/neilbalch/SimVascular-pythondemos/blob/master/contour_to_lofted_model.py script and I'm wearing my most accurate glasses.

**Comment by neilbalch** [comment]
> but you just need to check that the PolyData has points and cells, write out a pleasing error message if it doesn't.

Hrm, I'll look into this tomorrow.

> and I'm wearing my most accurate glasses.

Yea, it's me who needs to recheck his prescription. I never made a call to any vtk helper methods in that script, so I think it makes sense I never included it.

**Comment by neilbalch** [comment]
@ktbolt Oh and any other thoughts about what might be causing the issues with `segmentation.Circle.get_polydata()` returning none?

**Comment by ktbolt** [comment]
@neilbalch Like I said earlier, the  **segmentation.Circle.get_polydata()** returns **None** because you are not importing vtk in your script. Even though you are not using vtk in your script you are still returning vtk objects and Python doesn't know their type unless you import vtk.

**Comment by neilbalch** [comment]
Oh, that message never reached me. That's interesting...

**Comment by neilbalch** [comment]
Excellent! I'm back to the issue about the `Vmtk.cap_with_ids()` error message. I'm going to keep prodding, but I'm not sure how much I'll be able to find on my own.

**Comment by neilbalch** [comment]
@ktbolt (_ping_) Just wanted to make sure my previous message didn't slip through the cracks.

**Comment by ktbolt** [comment]
@neilbalch I'm not getting your edited messages. I'll make sure to check here daily.

I'm not sure what's required for `PolyData` that is not a model. VMTK doesn't know about SV models so it should support this. Have a look at the `sys_geom_cap_with_ids()` code and see what is going on there. 

If you don't know how to read a polydata surface mesh object into a modeler object then you haven't read the API documentation
```
help(sv.modeling)
```

Or if you have and it is not clear then I need to know so I can make it clear. You should also look at the test scripts.

**Comment by neilbalch** [comment]
@ktbolt 

> I'm not sure what's required for `PolyData` that is not a model. VMTK doesn't know about SV models so it should support this. Have a look at the `sys_geom_cap_with_ids()` code and see what is going on there.

I've tried, but I'm not really making any progress... figuring out the `ModelFaceID Array is not on the surface` detail is just about as far as I've been able to go.

> If you don't know how to read a polydata surface mesh object into a modeler object then you haven't read the API documentation
> 
> ```
> help(sv.modeling)
> ```
> 
> Or if you have and it is not clear then I need to know so I can make it clear. You should also look at the test scripts.

From what I can tell, only reading in from a designated `.vtp` file is supported? What if I have a Python object I want to use? Do I have to first write it out to a file somehow (?) and then import it back into a model object? That's a pretty unfortunate workaround if correct.

**Comment by neilbalch** [comment]
Hey @ktbolt, have you had any time to think about my previous message?

**Comment by ktbolt** [comment]
@neilbalch Well, you **could** just write out a file and read it back to create a model, that wouldn't disrupt the universe, sometimes you have to do whatever is required to get something working. 

You could modify the `sv.modeling.PolyData` constructor to accept a PolyData object or/and add a `set_surface()`  method to set the model geometry using an object, that's what I did
```
## Read PolyData.
file_name = "../data/models/loft-test-interpolate.vtp"
reader = vtk.vtkXMLPolyDataReader()
reader.SetFileName(file_name)
reader.Update()
read_polydata = reader.GetOutput()

## Create a model from the PolyData object.
model = sv.modeling.PolyData()
model.set_surface(surface=read_polydata)
```

**Comment by neilbalch** [comment]
@ktbolt Right, but I wanted to contribute my user recommendations seeing as how I think that's part of the task I've been given. I think that requiring user of a temporary file to be created is kludgy and should be avoided if possible.

Are you saying that you've implemented one/both of the possible fixes in the new API already? I'm not sure what you're trying to suggest here.

**Comment by neilbalch** [comment]
@ktbolt I've implemented the "surface → solid model → capped solid model" workflow in my script now, but it doesn't fix the:

> vmtk.Error: Vmtk.cap_with_ids() Error creating cap with ids.

I'm fairly confident this means that the API's behavior for capping models has changed since last year. I've confirmed that the `vtkPolyData` object given by `sv.modeling.PolyData().get_polydata()` has >1000 each of cells and points, so I don't think that's the issue. The `ModelFaceID Array is not on the surface` error message from the `Vmtk.cap_with_ids()` method is still the exception raised.

**Comment by ktbolt** [comment]
@neilbalch What if-statement in `sys_geom_cap_with_ids()` is causing it to print `ModelFaceID Array is not on the surface` and return an error? What is `ModelFaceID` ?

**Comment by neilbalch** [comment]
@ktbolt Line 510 of the file `sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx`. I'm on my phone right now, so I don't want to type out the entire line, but I included a picture of the relevant code section here.

![Screenshot_20200820-191316.png](https://user-images.githubusercontent.com/3847882/90844708-623bdf80-e319-11ea-836f-d9fd2036afec.png)

**Comment by neilbalch** [comment]
@ktbolt Re: https://github.com/SimVascular/SimVascular/issues/595#issuecomment-678045416

So are you saying that `sv.vmtk.cap_with_ids()` isn't the proper method to call because it has unclear behavior? Does this mean that `sv.vmtk.cap()` is the way to go? Do you have any theories for why the original Python API examples used the `cap_with_ids()` equivalent function and/or why it used to work fine but not anymore?

**Comment by ktbolt** [comment]
@neilbalch I'll fix this later this week, working on the **simulation** module.

**Comment by neilbalch** [comment]
@ktbolt Ooh, something else... How can I add the blended model to the SV DMG? It's returned as a `vtkPolyData` and not a model... so... how would that work.

**Comment by ktbolt** [comment]
No activity here, closing for now.
