### ISSUE TITLE
SV Python can't find standard library module

### ISSUE THREAD

**Issue by mrp089** [SimVascular/SimVascular#918]
I seem to have messed up my SV Python. After building a fresh SV and running `sv --python`, I get the following error (`lzma` is needed for another module):
```
>>> import lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pfaller/work/repos/SimVascular_fork/build/Externals-build/svExternals/bin/python-3.5.5/lib/python3.5/lzma.py", line 26, in <module>
    from _lzma import *
ImportError: No module named '_lzma'
```
This is strange since `lzma` is part of the [standard library](https://docs.python.org/3/library/lzma.html). Before I go deeper into debugging, have you seen this before @ktbolt?

I'm using Ubuntu 18.04 LTS, current SV master (19e6fb6f26600da0cbc99def4a93dcf377ddc7ac)

**Comment by ktbolt** [comment]
This also does not work on my Mac using SV master. 

The `_lzma.so` library is missing from `Externals-build/svExternals/bin/python-3.5.5/lib/python3.5/lib-dynload`.

**Comment by ktbolt** [comment]
@mrp089 I checked a few externals back to 2019, no `_lzma.so `library, don't think this was ever included in out Python 3.5 externals.

**Comment by mrp089** [comment]
Thank you for checking, @ktbolt! The module I was using is [`meshio`](https://pypi.org/project/meshio/1.8.9/). I can exclude it from my code. Do we want to include `lzma` in SV or can this be closed?

**Comment by ktbolt** [comment]
Well, the svExternals does have a `python-3.5.5/lib/python3.5/lzma.py` file so we should either remove that so that `lzma` is not a module or add the `_lzma.so` library. 

@osmsc Let's add the `_lzma.so` library, it might be useful.

**Comment by ktbolt** [comment]
No recent activity.
